### PR TITLE
Fix for Unescaped left brace in regex

### PR DESCRIPTION
**Pull request by machbio**
Fixed the Unescaped left brace in regex for Perl 5.21+ Versions

### CODE REVIEW

**Comment by ewels** [comment]
Nice! Could you add the new versions of Perl to the travis config file please, so that they are automatically checked as well?

**Comment by ewels** [comment]
Great! Have you run Cluster Flow after these changes? Are the braces still printed properly / do the submit commands still work?

**Comment by machbio** [comment]
Yes, I have run the Clusterflow - Everything works fine.

**Comment by ewels** [comment]
Nice, thanks! That was easier than I was expecting based on your original issue :)

**Pull request merged**
