### PR TITLE
Create salmon.cfmod.pl

### PR DESCRIPTION
**Pull request by darogan**
I messed up something in my last PR, so I'm trying again

Sorry about that

### CODE REVIEW

**Comment by darogan** [comment]
@ewels I don't understand the test failing here. Running `perl source/CF/cf_tests.pl` locally doesn't produce any errors for me.

**Comment by ewels** [comment]
Hi @darogan,

I just pulled your changes and got the same error. Running the command manually gives this error:
```
-bash: /Users/philewels/GitHub/Cluster_Flow/clusterflow/source/CF/../../modules/salmon.cfmod.pl: Permission denied
```

So just `chmod` the file to make it executable and everything should work I think. Let me know if you have difficulties and I can do it.

Phil

**Comment by ewels** [comment]
Hi @darogan,

I'll merge and make this change myself 😄 

Thanks again!

Phil

**Comment by ewels** [comment]
Checks passing with flying colours now! 🌈

**Comment by darogan** [comment]
Thanks @ewels. I had forgotten to do this - glad you sorted the permissions!

**Comment by ewels** [comment]
No problem! Thanks for writing the module :)

**Pull request merged**
