### PR TITLE
Fixes for #124 and #125

### PR DESCRIPTION
**Pull request by s-andrews**
This should add Lmod support and fix a bug in custom SLURM submit commands.

### CODE REVIEW

**Comment by s-andrews** [comment]
The CI checks failed for this, but it's all in Helpers.py which I didn't change!

**Comment by ewels** [comment]
Ah man, all this Python stuff - I'd totally forgotten that I'd written this!

**Comment by ewels** [comment]
Ok, so this is because the PyFlakes package that checks Python code has updated and now produces this warning. Should be an easy fix, will push it now.

**Comment by ewels** [comment]
Fix pushed, restarted the travis job 👍

**Comment by ewels** [comment]
All looking good! If you fancy adding something to the changelog and documentation too then that would be fab..

**Pull request merged**
